apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-mysql
  labels:
    app: vaultwarden
spec:
  ports:
    - port: 3306
  selector:
    app: vaultwarden
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-mysql
  labels:
    app: vaultwarden
spec:
  selector:
    matchLabels:
      app: vaultwarden
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vaultwarden
        tier: mysql
    spec:
      containers:
        - image: mariadb:11.4.4
          name: mysql
          env:
            - name: MARIADB_DATABASE
              value: vaultwarden
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-creds
                  key: password
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: vault-creds
                  key: username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-creds
                  key: password
            - name: MARIADB_CHARACTER_SET_SERVER
              value: utf8mb4
            - name: MARIADB_COLLATION_SERVER
              value: utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
